import mongoose from "mongoose"

const userSchema = new mongoose.Schema({
    username: {
        type: String,
        required: [true, "Please provide a username"],
        unique: true
    },
    email: {
        type: String,
        required: [true, "Please provide a email"],
        unique: true
    },
    password: {
        type: String,
        required: [true, "Please provide a password"],
    },
    isVerified: {
        type: Boolean,
        default: false,
    },
    isAdmin: {
        type: Boolean,
        default: false,
    },
    forgotPasswordToken: String,
    forgotPasswordTokenExpiry: Date,
    verifyToken: String,
    verifyTokenExpiry: Date,
})

// verifyToken is used to verify the user: it is a long gibberish string which is generated by api during the login of the user and one copy of this is sent and saved to the user's database document in mongodb and another copy is sent to the user or the browser. now this copy of the token in the browser is sent in your http request and the user is fetched from the mongoDB and then the copy of the verify token is matched with the one you got form the browser and if that matches, we will update the isVerified field of the user document as true, and the token generated will have a certain expiry and becasue of that the user/browser will have only a certain amount of time to get verified

// forgotPasswordToken : the copy is sent to the database and other to the user/browser/email and now the user will hit a route like forgotPassowrd or something and he will provide this token along with the new password to the api and the api will search in the database for the user document using this token and this will return you the user and the api will match the token and check the expiry and will allow the new password field to be set to the user document password  

// here if the model has already been created then we are choosing from the models array collection of the mongoose and if not then we are creating a brand new model called "User" using the schema "UserSchema" which will eventually be stored in the collection "users" 
// mongoose.models.User is a reference to a registered Mongoose model for a "users" collection. It is used to check if a model already exists to prevent overwrite errors, or to retrieve the existing model class to perform database operations without re-compiling the schema. so the first time it compiles the userschema to create the model but the next time it uses this already created model to initiate the document

const User = mongoose.models.User || mongoose.model("User", userSchema);

export default User;